apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j
  namespace: tsm-daba
spec:
  serviceName: neo4j-service
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
      - name: neo4j
        image: neo4j:latest
        ports:
        - containerPort: 7474
          name: http
        - containerPort: 7687
          name: bolt
        env:
        - name: NEO4J_AUTH
          valueFrom:
            secretKeyRef:
              name: dblp-secrets
              key: NEO4J_AUTH
        envFrom:
        - configMapRef:
            name: neo4j-config
        volumeMounts:
        - name: neo4j-data
          mountPath: /data
        - name: neo4j-import
          mountPath: /var/lib/neo4j/import
        resources:
          requests:
            memory: "4Gi"
            cpu: "1000m"
          limits:
            memory: "6Gi"
            cpu: "2000m"
        readinessProbe:
          httpGet:
            path: /
            port: 7474
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 7474
          initialDelaySeconds: 60
          periodSeconds: 30
      volumes:
      - name: neo4j-data
        persistentVolumeClaim:
          claimName: neo4j-data-pvc
      - name: neo4j-import
        persistentVolumeClaim:
          claimName: neo4j-import-pvc