apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-data-pvc
  namespace: tsm-daba
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
#  storageClassName: standard