apiVersion: v1
kind: ConfigMap
metadata:
  name: neo4j-config
  namespace: tsm-daba
data:
  NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
  NEO4J_PLUGINS: '["apoc", "apoc-extended"]'
  NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
  NEO4J_dbms_security_procedures_allowlist: "apoc.*"
  # Memory configuration
#  NEO4J_dbms_memory_pagecache_size: "2g"
#  NEO4J_dbms_memory_heap_initial__size: "2g"
#  NEO4J_dbms_memory_heap_max__size: "2g"
  # Performance optimizations
  NEO4J_dbms_checkpoint_interval_time: "60m"
  NEO4J_dbms_checkpoint_iops_limit: "2000"
  NEO4J_dbms_transaction_timeout: "60m"
#  NEO4J_dbms_lock_acquisition_timeout: "60s"
#  NEO4J_metrics_enabled: "false"
#  NEO4J_dbms_jvm_additional: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication -XX:MaxGCPauseMillis=300"
#  NEO4J_dbms_logs_query_enabled: "false"
#  NEO4J_dbms_transaction_state_allocation: "ON_HEAP"
#  NEO4J_dbms_memory_transaction_global_max_size: "1g"