apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-data-pv
  namespace: dblp-system
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/neo4j-data