version: '3.8'

services:
  neo4j:
    # Use the APOC-enabled image instead of the base image
    image: neo4j:5-enterprise
    container_name: advdaba_labo2_neo4j
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/testtest
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      # Enable APOC procedures
      - NEO4J_PLUGINS=["apoc", "apoc-extended"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
      # Memory configuration
      - NEO4J_dbms_memory_pagecache_size=1g
      - NEO4J_dbms_memory_heap_initial__size=1g
      - NEO4J_dbms_memory_heap_max__size=1g
      # Performance optimizations
      - NEO4J_dbms_checkpoint_interval_time=30m
      - NEO4J_dbms_checkpoint_iops_limit=1000
      - NEO4J_dbms_transaction_timeout=60m
      - NEO4J_dbms_lock_acquisition_timeout=30s
      - NEO4J_metrics_enabled=false
      - NEO4J_dbms_memory_heap_max__size=1g
    volumes:
#      - ./neo4j/data:/data
#      - ./neo4j/logs:/logs
      - neo4j-import:/var/lib/neo4j/import
#      - ./neo4j/plugins:/plugins
    deploy:
      resources:
        limits:
          memory: 3g
        reservations:
          memory: 2g
    healthcheck:
      test: ["CMD", "neo4j", "status"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - dblp-network
  my-dblp-loader:
    build:
      context: ..
      dockerfile: ./advdaba-docker/Dockerfile
    container_name: advdaba_labo2_loader
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      - DATABASE_URL=bolt://neo4j:7687
      - USER=neo4j
      - SECRET_KEY=testtest
      - MAX_ITEMS_PROCESSED=0
      - DEBUG=False
#      - FILE_URL=http://vmrum.isc.heia-fr.ch/test.json
#      - FILE_URL=http://vmrum.isc.heia-fr.ch/biggertest.json
      - FILE_URL=http://vmrum.isc.heia-fr.ch/dblpv13.json
      - BATCH_SIZE=200000
    #      - FILE_URL=http://vmrum.isc.heia-fr.ch/dblpv14.json
    volumes:
      - neo4j-import:/import
#      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 512m
    networks:
      - dblp-network
    command: python main.py

volumes:
  neo4j-import:

networks:
  dblp-network:
    driver: bridge